version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: shohelrana
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: solar
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_NAME: solar
      DB_USER: shohelrana
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432

    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    ports:
      - "3006:3006"
    depends_on:
      - backend

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db_data:
